name: Deploy to Remote Server

on: [push]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: echo "${{ secrets.GIT_PASSWORD }}" > ~/.git-credentials

    - name: SSH into remote server and update code
      uses: SamKirkland/FTP-Deploy-Action@4.0.0 
        with:
          server: 31.31.196.157
          username: u2085903
          password: b45SMOftTG4Bah49
          server-dir: memoracle/MemOracle/

