name: Deploy to Remote Server

on: [push]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: echo "${{ secrets.GIT_PASSWORD }}" > ~/.git-credentials

    - name: SSH into remote server and update code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        passphrase: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd memoracle/MemOracle/
          git pull &&
          pkill screen || true &&
          screen -S screen_bot -d -m bash -c 'source venv/bin/activate && python mem_bot.py'
